# Generated by Django 3.2.9 on 2022-08-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativochat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
